<?php

/* ***********************************************
 * Load and display parallel DFs in courses
 * generated by admin/lib/tools/parallelDF.php  
 * Author: J. Meyer                                                
/* *********************************************** */

require_once('functions.inc.php');
require_once('eql.inc.php');


// render page

$site->pageStart(array('popfit'=>1));

	$site->skin->submenuStart();
		echo '<b>Kurse</b> (in Vorbereitung, freigegeben, dauerhaft)<br><b>mit parallelen Durchf&uuml;hrungen</b> (Beginn, Ende, Ort identisch)<br><b>Update:</b> t&auml;glich</b>';
	$site->skin->submenuBreak();
		echo "&nbsp;";
	$site->skin->submenuEnd();
	
	$site->skin->workspaceStart();
	
	$filename = "lib/tools/parallel_df.html";
		
?>
		<style type="text/css">
			th, td, tf {
				text-align: left;
				vertical-align: top;
			}
			
			.grund, .url, .google {
				padding-right: 30px;
			}
			
			small {
				color: #555;
				margin-bottom: 10px;
				display: block;
			}
		</style>	
	<?php
	
	include($filename);
	
	$site->skin->workspaceEnd();
	
	$site->skin->buttonsStart();
		form_button('cancel', htmlconstant('_CANCEL'), 'window.close();return false;');
	$site->skin->buttonsEnd();
		
$site->pageEnd();
?>