<?php
/* ************************************************************************* */
/* TODO: 1.) use DB instead of protocol file, 2.) translate strings          */
/* Function:                                                                 */
/* This plugin outputs all addresses that have failed to geocode externally. */
/* The protocol file is a serialized array generated by                      */
/* core../wisy-sync-renderer-class.inc.php                                   */
/* Author: Jörg Meyer                                                        */
/* ************************************************************************* */

require_once('functions.inc.php');
require_once('eql.inc.php');

// render page
$site->pageStart(array('popfit'=>1));

$site->skin->submenuStart();
echo '<b>Nicht geokodierbare Adressen:</b>';
$site->skin->submenuBreak();
echo "&nbsp;";
$site->skin->submenuEnd();

$site->skin->workspaceStart();
$filename = "../files/logs/non_geocoded_adresses.dat";
$data = unserialize(file_get_contents($filename));

if(!is_array($data))
    die("Keine fehlerhaften Adressen vorliegend oder Protokolldatei nicht lesbar.");
				
?>
<style type="text/css">
    th, td, tf {
        text-align: left;
    }
			
    .grund, .url, .google {
        padding-right: 30px;
    }
</style>

<table>
 <thead>
  <tr>
	<th class='url'>Kurs mit folgender Adresse suchen</th>
	<th class='google'>Bei Google suchen</th>
	<th class='grund'>Fehler</th>
	<th class='gruppe'>Benutzergruppe</th>
	<th class='aenderung'>Letztes Update</th>
    <!-- <th class='datum'>Stand</th> -->
 </thead>
 <tfoot>
  <tr>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
    <!-- <td></td> -->
  </tr>
  </tfoot>
<tbody>
    <?php
    foreach($data AS $adresse) {
    
    /* ******************************
     * [error] => ..., [url] => ..., 
     * [adresse] => Array ([did], [strasse], [plz], [ort], [stadtteil], [land], [beginn], [ende], [beginnoptionen], [dauer], [preis], [kurstage], [tagescode], [zeit_von], [zeit_bis])
     * [df_id], [kurs_id], [date_modified], [user_grp], [user_grp_shortname]
     * ****************************** */
    
    $error = $adresse['error'];
    $error = str_replace("err_geocode_badxml", "Nicht gefunden", $error);
    $error = str_replace("err_geocode_missing_good_geocoder", "Portaleinstellung fehlt!", $error);
    				
    if(strpos($error, "err_geocode_fopen") !== FALSE && strpos($error, "openstreetmap.org") !== FALSE)
     $error = "Externer&nbsp;Kodierer&nbsp;falsch";
    				
    $strasse = $adresse['adresse']['strasse'];
    $ort = $adresse['adresse']['ort'];
    if(strlen(trim($strasse)) > 3)
     $ort = $strasse.",<br>".$ort;
    				
    if(strpos($error, "toomanycalls") === FALSE) {
    ?>	
    <tr>
    	<td><?php echo '<a href="/admin/edit.php?table=kurse&id='.$adresse['kurs_id'].'">'.$ort.'</a>';  ?></td>
    	<td><?php echo '<a href="https://www.google.de/search?q='.urlencode(str_replace("<br>", " ", utf8_encode($ort))).'" target="_blank">&rarr;</a>'; // https://www.google.de/maps/place/ ?></td> 
    	<td><?php $x = strpos($error, "--"); if($x !== FALSE) { $error = substr($error, 0, $x); } echo $error; ?></td>
    	<td><?php echo $adresse['user_grp_shortname']; ?></td>
    	<td><?php echo $adresse['date_modified']; ?></td>
        <!-- <td><?php /* echo date("Y-m-d", filemtime($filename)); */ ?></td> -->
    </tr>
    <?php
    }
    
    } // End: foreach address
    ?>
</tbody>
</table>

<?php
$site->skin->workspaceEnd();
	
$site->skin->buttonsStart();
form_button('cancel', htmlconstant('_CANCEL'), 'window.close();return false;');
$site->skin->buttonsEnd();
		
$site->pageEnd();


?>