<?php
//
// Place exactly one statement per line, no additional linewraps.
// Do not use any operators for string creation.
// Do not use other remarks than // at the beginning of a line.
//
// In this file the tips'n'tricks for the program are defined. Use _TIP_0000 up to _TIP_9999 for the tips. Gaps are allowed. System-specific tips should be defined in the file 'config/lang/tipsntricks', in this file you can also overwrite the tips defined here.
//
help_define('_TIP_0000',        "Das Programm bietet Ihnen an, beim jeder Anmeldung einen '''Tip oder einen Trick''' zu zeigen. Falls Sie die Tips nicht wünschen, können Sie diese oben rechts unter \"Einstellungen / Ansicht / Tips und Tricks\" ausschalten.");
help_define('_TIP_0010',        "Sie gelangen zur Datensatzübersicht einer Tabelle durch Klick auf eine Registerkarte am oberen Bildschrirmrand. Seltener verwendete Tabellen sind unter \"Etc.\" zusammengefaßt. \n\nUm alle Datensätze, auf die Sie Zugriff haben zu sehen, klicken  Sie in der Tabellenübersicht oben auf \"Alle\".");
help_define('_TIP_0020',        "Sie gelangen zur Detailansicht eines Datensatzes indem Sie in der Datensatzübersicht auf den entsprechenden Datensatz klicken. In der Detailansicht sehen Sie alle Felder auf die Sie Zugriff haben bzw. können diese auch ändern.");
help_define('_TIP_0030',        "Sie haben zwei Möglichkeiten einen Datensatz in der Detailansicht zu speichern:\n\n- Klicken Sie unten auf \"OK\" wird der Datensatz gespeichert und Sie gelangen zurück in die Datensatzübersicht.\n- Klicken Sie unten auf \"übernehmen\", wird der Datensatz gespeichert und Sie bleiben in der Detailansicht.\n\nAch so: \"Abbruch\" bringt Sie zurück zur Datensatzübersicht ''ohne'' den Datensatz zu speichern.");
help_define('_TIP_0040',        "Durch Klick auf die meisten Spaltennamen in der Datensatzübersicht einer Tabelle können Sie die Sortierung einstellen - Sie erkennen die momentane Sortierung an einem Pfeil neben dem Spaltennamen.\n\nDurch einen weiteren Klick auf den Spaltennamen schalten Sie zwischen auf- und absteigender Sortierung hin und her.");
help_define('_TIP_0050',        "Sie können die in der Datensatzübersicht anzuzeigenden Spalten oben rechtes unter \"Einstellungen / Spalten\" festlegen.");
help_define('_TIP_0060',        "In der Datensatzübersicht einer Tabellen können Sie sich nur Datensätze anzeigen lassen, die bestimmten Kriterien genügen.\n\nWählen Sie hierzu einen Feldnamen aus dem Popup oben links aus und geben Sie den gewünschten Wert in das danebenliegene Eingabefeld ein.\n\nEin Klick auf \"Suchen\" zeigt Ihnen dann die entsprechenden Datensätze an. Wenn Sie wieder alle Datensätze, auf die Sie Zugriff haben, sehen möchten klicken Sie oben auf \"Alle\".");
help_define('_TIP_0070',        "Weiterführende Informationen erhalten Sie über die kontext-sensitive Funktion \"Hilfe\" oben rechts.\n\nDort finden Sie unter \"Index\" auch eine übersicht aller verfügbaren Hilfethemen.");
help_define('_TIP_0080',        "Sie können die Suche nach Datensätzen verfeinern indem Sie in der Datensatzübersicht auf \"Suche erweitern\" klicken.\n\nDas Programm bietet Ihnen dann eine Liste an, die Sie mit Ihren Suchkriterien füllen können und mit UND oder ODER verknüpfen können.\n\nBenötigen Sie weitere Eingabefelder, klicken Sie einfach erneut auf \"Suche erweitern\".");
help_define('_TIP_0090',        "über das Symbol \"Einstellungen\" oben rechts können Sie zahlreiche Einstellungen vornehmen. Die Einstellungen sind kontext-sesitiv, d. h. es werden Ihnen immer die Optionen angeboten, die in der akutellen Ansicht sinnvoll sind:\n\nSo können Sie in der Datensatzübersicht z. B. die anzuzeigenden Spalten festlegen und in der Detailansicht die Größe der Eingabefelder bestimmen.\n\nDie Einstellungen werden permanent gespeichert und stehen Ihnen beim nächsten Login sogar auf einem anderen Rechner wieder zur Verfügung.");
help_define('_TIP_0100',        "Wenn Sie in der Datensatzübersicht über einen Datensatz mit der Maus fahren wird die Zeile normalerweise optisch hervorgehoben. Sie können Sie dieses Verhalten mit der Option \"Einstellungen / Ansicht / Datensatz unter Maus hervorheben\" ändern.");
help_define('_TIP_0110',        "Sie können einen Datensatz nur dann löschen, wenn er nicht mehr von anderen referenziert wird, d. h. wenn keine Verweise von anderen Datensätzen auf den zu löschenden Datensatz existieren.\n\nUm einen Datensatz zu löschen müssen also zunächst alle Referenzen entfernt werden.\n\nEtwaige Referenzen werden können Sie sich in der Detailansicht unter \"Referenzen\" anzeigen lassen.");
help_define('_TIP_0130',        "In der Detailansicht bringen Sie die Funktionen \"<< Zurück\" und \"Vor >>\" zum vorherigen/nächsten Datensatz aus dem aktuellen Ausschnitt der Datensatzübersicht.\n\nD. h. wenn in der Datensatzübersicht z. B. 10 von 100 Datensätzte sichtbar sind, können Sie mit \"<< Zurück\" und \"Vor >>\" in den 10 Datensätzen blättern.");
help_define('_TIP_0150',        "Ein Datensatz wird i. d. R. über eine zweite Reihe von Karteikartenreitern logisch unterteilt.\n\nSie können Sie dieses Verhalten mit der Option \"Einstellungen / Ansicht / Datensätze mit Karteikarten unterteilen\" ändern: Schalten Sie die Option aus, so werden die Bereiche einfach untereinander dargestellt.");
help_define('_TIP_0160',        "Das System verfügt über ein ausgeklügeltes Rechtemanagement - Sie bekommen nur die Datensätze und Felder zu Gesicht, die für Sie vorgesehen sind oder die Sie selbst erstellt haben.\n\nHierzu unterscheidet das System für jeden Datensatz verschiedene Rechte für den ''Eigentümer'' eines Datensatzes, der ''Benutzergruppe'', dem ein Datensatz zugeordnet ist und ''allen Anderen''\n\nSie können diese Rechte in der Detailansicht eines Datensatzes unter \"Rechte\" einsehen und u. U. auch ändern.");
help_define('_TIP_0170',        "I. d. R. sind alle Benutzer - also auch Sie - einer oder mehrern ''Benutzergruppen'' zugeordnet.\n\nWelchen Benutzergruppen Sie zugeordnet sind sehen Sie unter \"Einstellungen / Filter / Benutzergruppen\". Hier können Sie auch die Datensätze bestimmter Benutzergruppen ausblenden.");
help_define('_TIP_0180',        "Normalerweise werden Datensätze, auf die Sie keinen Zugriff haben aus der Datensatzübersicht einer Tabelle ausgeblendet.\n\nSie können sich die Existenz dieser Datensätze auch anzeigen lassen, indem Sie unter \"Einstellungen / Filter / Bei fehlenden Rechten\" die Option \"Hinweis anzeigen\" wählen. Einsehen oder gar ändern können Sie diese Datensätze natürlich trotzdem nicht.");
help_define('_TIP_9999',        "Sie haben jetzt alle Tips gelesen und können diese nun unter \"Einstellungen / Ansicht / Tips und Tricks\" ausschalten. Andernfalls werden alle Tips von vorne angezeigt.");
help_define('_TIP_DIDYOUKNOW',  "'''Wußten Sie schon...'''");
help_define('_TIP_TIPSNTRICKS', "Tips'n'Tricks");
// This is the title of the tips'n'tricks window, used beside _TIP_DIDYOUKNOW.
?>